#!/usr/bin/expect -f
# Wird im Cronjob virtelstündig (oder so) ausgeführt
spawn scp "Jufo@ip:/home/Jufo/datenbank.db" /home/Jufo/Audiosystem

expect {
  -re ".*es.*o.*" {
    exp_send "yes\r"
    exp_continue
  }
  -re ".*sword.*" {
    exp_send "PASSWORD\r"
  }
}
interact
